### ISSUE TITLE
디스코드 임베드에 컬러 적용

### ISSUE THREAD

**Issue by zero734kr** [cjaewon/letterbot#5]
"#FFFFFF" 형식이 아닌 0xFFFFFF 형식으로 적으시면 될거 같습니다.

[출처](https://www.reddit.com/r/discordapp/comments/6ov372/how_does_the_color_code_for_bot_embeds_work/)

**Comment by cjaewon** [comment]
예전에 #FFF 라 했을 때는 오류가 떳는데 0xFFF 라고 해야하네요.
이슈 감사합니다 😊
